export const API_ROUTES = {
  PLAY: '/api/play/get-play',
  LOGIN: '/api/global/login',
  REGISTER: `/api/user/signup-user`,
  GET_QUESTION: `/api/user/get-question`,
  SECURITY_ANSWER: `/api/user/:userId/security-answers`,
  GET_ALL_USERS: '/api/user/get-users-data',
  UPDATE_USERS: '/api/user/:itemId/update-user',
  UPDATE_VALUES: `/api/array/item-update/:userId`,
  FILTER_LEVEL: `/api/play/by-level/:level`,
  TIME: '/api/time/get-time',
  GET_SESSION_WORD: '/api/mcq/get-session-words',
  GET_ALL_MCQ: `/api/mcq`,
  POST_JUMBLE_WORDS: `/api/mcq/add-words`,
  GET_SINGLE_USER: `/api/user/get-user/:userId`,
  POST_ADD_PLAY_DATA: `/api/play`,
  FILTER_PLAY_LEVELS: `/api/play/levels`,
  VALUES: '/api/array/items',
  GET_VALUE_BY_ID: `/api/array/items/:itemId`,
  DELETE_VALUE: `/api/array/item-delete/:itemId`,
  DELETE_ALL_VALUE: `/api/array/item-delete`,

  ADMIN: {
    PROFILE: `/api/admin/admin-data`,
    UPDATE_PROFILE: `/api/admin/update-admin/:adminId`,
    GET_USERS_LIST: `/api/user/get-users`,
    GET_ALL_USERS_DATA: `/api/user/get-users-data`,
    GET_SINGLE_USER: `/api/user/get-user/:userId`,
    USER_REPORT: `/api/user/download-user-play-pdf`,
    UPDATE_USER: `/api/user/:userId/update-user`,
    DELETE_USER: `/api/user/:userId/delete-user`,
    GET_QUESTIONS: `/api/user/get-question`,
    ADD_QUESTION: `/api/admin/add-question`,
    UPDATE_QUESTION: `/api/admin/security-questions-update/:questionId`,
    DELETE_QUESTION: `/api/admin/security-questions-delete/:questionId`,
    GET_JUMBLE_WORDS: `/api/mcq/`,
    DELETE_JUMBLE_WORDS: `/api/mcq/delete/:id`,
    POST_JUMBLE_WORDS: `/api/mcq/add-words`,
    UPDATE_JUMBLE_WORDS: `/api/mcq/update/:id`,

    POST_BG_IMAGES: '/api/admin/bg-img',
    GET_BG_IMAGES: '/api/admin/bg-img',
    PATCH_BG_IMAGES: '/api/admin/bg-img/:id',
    DELETE_BG_IMAGES: '/api/admin/bg-img/:id',

    GET_ALL_TIME: `/api/time/get-time`,
    POST_ALL_TIME: `/api/time/create-time`,
    PATCH_ALL_TIME: `/api/time/update-time`,

    DOWNLOAD_CSV: `/api/user/generate-csv/all-users-play`,

    POST_VALUE: `/api/array/item-add`,
    PATCH_VALUE: `/api/array/item-update/:itemId`,

    GET_MODAL: `/api/admin/models`,
    POST_MODAL: `/api/admin/models`,
    PATCH_MODAL: `/api/admin/models/:id`,
    DELETE_MODAL: `/api/admin/models/:id`,

    POST_AGREEMENT: '/api/admin/agreement',
    GET_AGREEMENT: '/api/admin/agreement',
    PATCH_AGREEMENT: '/api/admin/agreement',
    DELETE_AGREEMENT: '/api/admin/agreement/:id',
  },

  MONKEY: {
    GET: '/api/admin/surveymonkey',
    POST: '/api/admin/surveymonkey/:adminId',
    PATCH: '/api/admin/surveymonkey/:adminId',
  },
}
